#! /bin/bash
TestSuite=raid-sdb-13

Fio=/usr/local/bin/fio

Disk=/dev/sdb

DataSize=500g
Logdir=/home/ren/fio/log
Taskdir=/home/ren/fio/task
Runtime=120

LogFile=$Logdir/$TestSuite-test.log

# ioengine
ioengines="sync libaio posixaio"
# rw
rws="read write randread randwrite"
# is 17
bss="64 128 256 512 1k 2k 4k 8k 16k 32k 64k 128k 256k 512k 1m 2m 4m"
# is 7
iodepths="1 4 16 64"

