#! /bin/bash

TestSuite=ssd

Fio=/usr/local/bin/fio

DataSize=100g
Logdir=/home/ren/fio/log
Taskdir=/home/ren/fio/task

LogFile=$Logdir/$TestSuite-test.log

# ioengine
ioengines="libaio sync"
# rw
rws="read write randread randwrite"
# is 16
bss="16k 32k 64k 128k 256k 512k 1m 2m 4m"
# is 7
iodepths="1 4 16 64"

