#! /bin/bash

Testsuite=rdma

RFTP_HOME=/home/ren/rftp

Rcftp=/usr/bin/rcftp
Configdir=$RFTP_HOME/jss/$Testsuite/config
Taskdir=$RFTP_HOME/jss/$Testsuite/task
Logdir=$RFTP_HOME/jss/$Testsuite/log
SourceDir=$RFTP_HOME/data/source
SinkDir=$RFTP_HOME/data/sink

Iter=35

ServIP=192.168.14.17
ServPort=9987

cbufsizs="2M"
cbufnums="100"
rcstreamnums="1"

numofclients="1 2 4 8 16 32"

