# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 3

# SIMPLE=simple_write simple_read
# COPY=copy_system copy_block copy_stdio
DIR=printdir
# MMAP=mmap

ALL= $(DIR)

all: $(ALL)

clean:
	@rm -f $(ALL) file.out records.dat *~
