#! /bin/bash

Fio=/usr/local/bin/fio

Testsuite=rocelat

DataSize=100g
Logdir=/home/ren/fio/log/$Testsuite
Taskdir=/home/ren/fio/task/$Testsuite

LogFile=$Logdir/$Testsuite.log

ServIP=192.168.2.9
ServPort=19001


# is 16
bss="512 1k 2k 4k 8k 16k 32k 64k 128k 256k 512k 1m 2m 4m 8m 16m"
# is 7
iodepths="1 2 4 8 16 32 64"

