#! /bin/bash

#Testcase=mongodb-nc-onet
Testcase=mongodb-default-onet

YCSBHOME=~/ycsb/YCSB

Logdir=~/ycsb/log-$Testcase
Taskdir=~/git/farm/ycsb/workloads

wls="wlonet-read100-up0 wlonet-read90-up10 wlonet-read80-up20 wlonet-read50-up50"
