#! /bin/bash

# for HP/AMD architecture

TestSuite=ssd

Fio=/usr/local/bin/fio

DataSize=100g
Logdir=/home/ren/numa/fio/log
Taskdir=/home/ren/numa/fio/task

LogFile=$Logdir/$TestSuite-test.log

# numa node to be tested
cpunodes="4 5 0 2"
memnodes="4 5 0 2"

# ioengine
ioengines="libaio sync"
# rw
rws="read write randread randwrite"
# is 9
bss="512k 1m 2m 4m 8m"
# is 7
iodepths="1 4 16"

