#! /bin/bash

# for HP/AMD architecture

TestSuite=ssd-sdc

Fio=/usr/local/bin/fio

DataSize=100g
Logdir=/home/ren/numa/fio/log
Taskdir=/home/ren/numa/fio/task

LogFile=$Logdir/$TestSuite-test.log

# numa node to be tested
cpunodes="0 1 2 3 4 5 6 7"
memnodes="0 1 2 3 4 5 6 7"

runtime=60s

# ioengine
ioengines="sync libaio"
# rw
#rws="read write randread randwrite"
rws="read write"
# is 5
bss="128k 512k 1m 2m 4m 8m"
# is 7
iodepths="1 4 16"

