#! /bin/bash

TestSuite=tgt-latency-default

Fio=/usr/local/bin/fio

DataSize=400g
Runtime=60
Logdir=/home/ren/fio/tgt/log-$TestSuite
Taskdir=/home/ren/fio/tgt/task-$TestSuite
Parsedir=/home/ren/fio/tgt/parse-$TestSuite

LogFile=$Logdir/$TestSuite-test.log
DateFile=$Logdir/testcase-date-start-end.log

# ioengine
ioengines="sync"
# rw
rws="randread"
# is 7
bss="4k 8k 16k 32k 64k 128k 256k 512k"

