#! /bin/bash

Fio=/usr/local/bin/fio

DataSize=100g
Logdir=/home/ren/fio/log
Taskdir=/home/ren/fio/task

LogFile=$Logdir/rdma-test.log

ServIP=192.168.53.17
ServPort=19001


# is 4
bss="64k 256k 1m 4m "
# is 7
iodepths="1 16 64"

# numa node to be tested
cpunodes="0 1 2 4 6"
memnodes="0 1 2 4 6"

